name: copies
on:
  push:
    branches:
      - '**'
jobs:
  copies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: cp TangerineUI.css mastodon/app/javascript/styles/tangerineui/tangerineui.scss
      - run: cp TangerineUI-purple.css mastodon/app/javascript/styles/tangerineui-purple/tangerineui-purple.scss
      - run: cp TangerineUI-cherry.css mastodon/app/javascript/styles/tangerineui-cherry/tangerineui-cherry.scss
      - run: cp TangerineUI-lagoon.css mastodon/app/javascript/styles/tangerineui-lagoon/tangerineui-lagoon.scss
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Copy CSS files to installation folder
          file_pattern: 'mastodon/'
